apiVersion: 1
datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    version: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
  - name: Grafana Pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040
    jsonData:
      minStep: '15s'
